// frontends/vue/src/examples/editable-text.vue
<!-- Commit an edited greeting when the text field loses focus. -->
<script setup>
import { ref } from 'vue'

const text = ref('Hello World')
const draft = ref(text.value)
</script>

<template>
  <h1>Editable text</h1>
  <div class="description">Edit the greeting text.</div>
  <div class="controls">
    <label for="text">Text</label>
    <input id="text" v-model="draft" @blur="text = draft">
  </div>
  <label class="demo-output">MyText<input readonly :value="text" /></label>
</template>

// frontends/react/src/examples/editable-text.jsx
import { useState } from 'react'

// Commit an edited greeting when the text field loses focus.
export default function EditableText() {
  const [text, setText] = useState('Hello World')
  const [draft, setDraft] = useState(text)

  return (
    <>
      <h1>Editable text</h1>
      <div className="description">Edit the greeting text.</div>
      <div className="controls">
        <label htmlFor="text">Text</label>
        <input id="text" value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={() => setText(draft)} />
      </div>
      <label className="demo-output">MyText<input readOnly value={text} /></label>
    </>
  )
}
