// frontends/vue/src/examples/text-color.vue
<!-- Add a live text color control to the editable greeting. -->
<script setup>
import { ref } from 'vue'

const text = ref('Hello World')
const draft = ref(text.value)
const textColor = ref('#223044')
</script>

<template>
  <h1>Text color</h1>
  <div class="description">Choose the text color.</div>
  <div class="controls">
    <label for="text">Text</label>
    <input id="text" v-model="draft" @blur="text = draft">
    <label for="text-color">Text color</label>
    <input id="text-color" v-model="textColor" type="color" @input="textColor = $event.currentTarget.value">
  </div>
  <label class="demo-output">MyText<input readonly :value="text" :style="{ color: textColor }" /></label>
</template>

// frontends/react/src/examples/text-color.jsx
import { useState } from 'react'

// Add a live text color control to the editable greeting.
export default function TextColor() {
  const [text, setText] = useState('Hello World')
  const [draft, setDraft] = useState(text)
  const [textColor, setTextColor] = useState('#223044')

  return (
    <>
      <h1>Text color</h1>
      <div className="description">Choose the text color.</div>
      <div className="controls">
        <label htmlFor="text">Text</label>
        <input id="text" value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={() => setText(draft)} />
        <label htmlFor="text-color">Text color</label>
        <input id="text-color" type="color" value={textColor} onInput={(event) => setTextColor(event.currentTarget.value)} />
      </div>
      <label className="demo-output">MyText<input readOnly value={text} style={{ color: textColor }} /></label>
    </>
  )
}
