// frontends/react/src/examples/background-color.jsx
import { useState } from 'react'

// Add a live background color control to the styled greeting.
export default function BackgroundColor() {
  const [text, setText] = useState('Hello World')
  const [draft, setDraft] = useState(text)
  const [textColor, setTextColor] = useState('#223044')
  const [backgroundColor, setBackgroundColor] = useState('#ffffff')

  return (
    <>
      <h1>Background color</h1>
      <div className="description">Choose the background color.</div>
      <div className="controls">
        <label htmlFor="text">Text</label>
        <input id="text" value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={() => setText(draft)} />
        <label htmlFor="text-color">Text color</label>
        <input id="text-color" type="color" value={textColor} onInput={(event) => setTextColor(event.currentTarget.value)} />
        <label htmlFor="background-color">Background color</label>
        <input id="background-color" type="color" value={backgroundColor} onInput={(event) => setBackgroundColor(event.currentTarget.value)} />
      </div>
      <label className="demo-output">MyText<input readOnly value={text} style={{ color: textColor, backgroundColor }} /></label>
    </>
  )
}

// frontends/vue/src/examples/background-color.vue
<!-- Add a live background color control to the styled greeting. -->
<script setup>
import { ref } from 'vue'

const text = ref('Hello World')
const draft = ref(text.value)
const textColor = ref('#223044')
const backgroundColor = ref('#ffffff')
</script>

<template>
  <h1>Background color</h1>
  <div class="description">Choose the background color.</div>
  <div class="controls">
    <label for="text">Text</label>
    <input id="text" v-model="draft" @blur="text = draft">
    <label for="text-color">Text color</label>
    <input id="text-color" v-model="textColor" type="color" @input="textColor = $event.currentTarget.value">
    <label for="background-color">Background color</label>
    <input id="background-color" v-model="backgroundColor" type="color" @input="backgroundColor = $event.currentTarget.value">
  </div>
  <label class="demo-output">MyText<input readonly :value="text" :style="{ color: textColor, backgroundColor }" /></label>
</template>
