// frontends/react/src/App.jsx
import { useEffect, useState } from 'react'

const editableFields = ['customer', 'quantity', 'note', 'fulfilled']

function copyDraft(order) {
  return order
    ? Object.fromEntries(editableFields.map((field) => [field, order[field]]))
    : null
}

async function request(path, options) {
  let response
  try {
    response = await fetch(path, options)
  } catch {
    throw new Error('Could not reach the server. Please try again.')
  }

  if (!response.ok) {
    let message = `Request failed (${response.status}).`
    try {
      const body = await response.json()
      if (typeof body.detail === 'string') message = body.detail
    } catch {
      // Keep the status-based fallback for non-JSON responses.
    }
    throw new Error(message)
  }
  return response.json()
}

function App() {
  const [orders, setOrders] = useState([])
  const [selectedId, setSelectedId] = useState(null)
  const [draft, setDraft] = useState(null)
  const [busy, setBusy] = useState(true)
  const [feedback, setFeedback] = useState('Loading orders…')

  const selected = orders.find((order) => order.id === selectedId)

  async function loadOrders(path = '/api/orders') {
    setBusy(true)
    setFeedback(path === '/api/reset' ? 'Resetting demo…' : 'Loading orders…')
    try {
      const nextOrders = await request(path, path === '/api/reset' ? { method: 'POST' } : undefined)
      setOrders(nextOrders)
      const first = nextOrders[0] ?? null
      setSelectedId(first?.id ?? null)
      setDraft(copyDraft(first))
      setFeedback('')
    } catch (error) {
      setFeedback(error.message)
    } finally {
      setBusy(false)
    }
  }

  useEffect(() => {
    loadOrders()
  }, [])

  function selectOrder(order) {
    setSelectedId(order.id)
    setDraft(copyDraft(order))
    setFeedback('')
  }

  function updateDraft(field, value) {
    setDraft((current) => ({ ...current, [field]: value }))
  }

  async function save(event) {
    event.preventDefault()
    if (!selected || !draft || busy) return

    setBusy(true)
    setFeedback('Saving order…')
    try {
      const saved = await request(`/api/orders/${selected.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...draft,
          quantity: Number(draft.quantity),
        }),
      })
      setOrders((current) => current.map((order) => (order.id === saved.id ? saved : order)))
      setDraft(copyDraft(saved))
      setFeedback('Order saved.')
    } catch (error) {
      setFeedback(error.message)
    } finally {
      setBusy(false)
    }
  }

  const total = selected && draft
    ? (Number(draft.quantity) * selected.unit_price_cents) / 100
    : 0

  return (
    <main className="app">
      <nav aria-label="Implementations">
        <a href="/react/" aria-current="page">React</a>
        <a href="/vue/">Vue</a>
        <a href="/pages/">Genro Pages</a>
      </nav>
      <h1>Order editor — React</h1>
      <p className="hint">
        Quantity totals update after each edit. Selecting another order or resetting the demo discards unsaved changes.
      </p>

      <div className="layout">
        <section className="panel" aria-labelledby="orders-heading">
          <h2 id="orders-heading">Orders</h2>
          <div className="order-list">
            {orders.map((order) => (
              <button
                type="button"
                key={order.id}
                data-testid={`order-${order.id}`}
                aria-pressed={order.id === selectedId}
                disabled={busy}
                onClick={() => selectOrder(order)}
              >
                #{order.id} — {order.customer}
              </button>
            ))}
          </div>
        </section>

        <section className="panel" aria-labelledby="editor-heading">
          <h2 id="editor-heading">Order details</h2>
          {selected && draft ? (
            <form onSubmit={save}>
              <label className="field">
                Customer
                <input
                  data-testid="customer"
                  type="text"
                  value={draft.customer}
                  disabled={busy}
                  onChange={(event) => updateDraft('customer', event.target.value)}
                />
              </label>
              <label className="field">
                Product
                <input type="text" value={selected.product} readOnly disabled={busy} />
              </label>
              <label className="field">
                Unit price
                <input type="text" value={`EUR ${(selected.unit_price_cents / 100).toFixed(2)}`} readOnly disabled={busy} />
              </label>
              <label className="field">
                Quantity
                <input
                  data-testid="quantity"
                  type="number"
                  value={draft.quantity}
                  disabled={busy}
                  onChange={(event) => updateDraft('quantity', event.target.value)}
                />
              </label>
              <label className="field">
                Note
                <input
                  data-testid="note"
                  type="text"
                  value={draft.note}
                  disabled={busy}
                  onChange={(event) => updateDraft('note', event.target.value)}
                />
              </label>
              <label className="check">
                <input
                  data-testid="fulfilled"
                  type="checkbox"
                  checked={draft.fulfilled}
                  disabled={busy}
                  onChange={(event) => updateDraft('fulfilled', event.target.checked)}
                />
                Fulfilled
              </label>
              <p className="total">Total: <span data-testid="total">EUR {Number.isFinite(total) ? total.toFixed(2) : '0.00'}</span></p>
              <div className="actions">
                <button className="primary" data-testid="save" type="submit" disabled={busy}>Save</button>
                <button data-testid="reset" type="button" disabled={busy} onClick={() => loadOrders('/api/reset')}>Reset demo</button>
              </div>
            </form>
          ) : (
            <p className="meta">No order is available.</p>
          )}
          <p className="feedback" data-testid="feedback" role="status" aria-live="polite">{feedback}</p>
          {!selected && (
            <div className="actions">
              <button data-testid="reset" type="button" disabled={busy} onClick={() => loadOrders('/api/reset')}>Reset demo</button>
            </div>
          )}
        </section>
      </div>
    </main>
  )
}

export default App

// frontends/vue/src/App.vue
<script setup>
import { computed, onMounted, ref } from 'vue'

const orders = ref([])
const selectedId = ref(null)
const draft = ref(null)
const feedback = ref('')
const busy = ref(false)

const total = computed(() => {
  if (!draft.value) return 'EUR 0.00'
  const quantity = Number(draft.value.quantity)
  const cents = Number.isFinite(quantity)
    ? quantity * draft.value.unit_price_cents
    : 0
  return `EUR ${(cents / 100).toFixed(2)}`
})

function makeDraft(order) {
  return order ? { ...order } : null
}

function selectOrder(order) {
  if (busy.value) return
  selectedId.value = order.id
  draft.value = makeDraft(order)
  feedback.value = ''
}

function selectFirst(nextOrders) {
  const first = nextOrders[0] ?? null
  selectedId.value = first?.id ?? null
  draft.value = makeDraft(first)
}

function errorMessage(error) {
  return error instanceof Error ? error.message : 'The request failed.'
}

async function request(url, options) {
  const response = await fetch(url, options)
  let body = null
  try {
    body = await response.json()
  } catch {
    // A proxy or server failure may return an empty or non-JSON response.
  }
  if (!response.ok) {
    throw new Error(body?.detail || `Request failed (${response.status}).`)
  }
  return body
}

async function loadOrders() {
  busy.value = true
  feedback.value = 'Loading orders…'
  try {
    const nextOrders = await request('/api/orders')
    orders.value = nextOrders
    selectFirst(nextOrders)
    feedback.value = ''
  } catch (error) {
    orders.value = []
    selectFirst([])
    feedback.value = `Could not load orders: ${errorMessage(error)}`
  } finally {
    busy.value = false
  }
}

async function saveOrder() {
  if (busy.value || !draft.value) return
  busy.value = true
  feedback.value = 'Saving…'
  const id = draft.value.id
  const payload = {
    customer: draft.value.customer,
    quantity: Number(draft.value.quantity),
    note: draft.value.note,
    fulfilled: draft.value.fulfilled,
  }
  try {
    const saved = await request(`/api/orders/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
    orders.value = orders.value.map((order) =>
      order.id === saved.id ? saved : order,
    )
    draft.value = makeDraft(saved)
    feedback.value = 'Order saved.'
  } catch (error) {
    feedback.value = `Could not save order: ${errorMessage(error)}`
  } finally {
    busy.value = false
  }
}

async function resetDemo() {
  if (busy.value) return
  busy.value = true
  feedback.value = 'Resetting…'
  try {
    const nextOrders = await request('/api/reset', { method: 'POST' })
    orders.value = nextOrders
    selectFirst(nextOrders)
    feedback.value = 'Demo reset.'
  } catch (error) {
    feedback.value = `Could not reset demo: ${errorMessage(error)}`
  } finally {
    busy.value = false
  }
}

onMounted(loadOrders)
</script>

<template>
  <main class="app">
    <nav aria-label="Implementations">
      <a href="/react/">React</a>
      <a href="/vue/" aria-current="page">Vue</a>
      <a href="/pages/">Genro Pages</a>
    </nav>

    <h1>Vue order editor</h1>
    <p class="hint">
      Changes are local until Save. Leaving a quantity field updates the total;
      selecting another order or resetting the demo discards unsaved changes.
    </p>

    <div class="layout">
      <section class="panel" aria-labelledby="orders-heading">
        <h2 id="orders-heading">Orders</h2>
        <div class="order-list">
          <button
            v-for="order in orders"
            :key="order.id"
            type="button"
            :data-testid="`order-${order.id}`"
            :aria-pressed="selectedId === order.id"
            :disabled="busy"
            @click="selectOrder(order)"
          >
            #{{ order.id }} — {{ order.customer }}
          </button>
        </div>
      </section>

      <section class="panel" aria-labelledby="editor-heading">
        <h2 id="editor-heading">Order details</h2>
        <form v-if="draft" novalidate @submit.prevent="saveOrder">
          <label class="field">
            Customer
            <input
              v-model="draft.customer"
              data-testid="customer"
              type="text"
              :disabled="busy"
            />
          </label>

          <label class="field">
            Product
            <input
              :value="draft.product"
              data-testid="product"
              type="text"
              readonly
              :disabled="busy"
            />
          </label>

          <label class="field">
            Unit price
            <input
              :value="`EUR ${(draft.unit_price_cents / 100).toFixed(2)}`"
              data-testid="unit-price"
              type="text"
              readonly
              :disabled="busy"
            />
          </label>

          <label class="field">
            Quantity
            <input
              v-model.number="draft.quantity"
              data-testid="quantity"
              type="number"
              :disabled="busy"
            />
          </label>

          <label class="field">
            Note
            <input
              v-model="draft.note"
              data-testid="note"
              type="text"
              :disabled="busy"
            />
          </label>

          <label class="check">
            <input
              v-model="draft.fulfilled"
              data-testid="fulfilled"
              type="checkbox"
              :disabled="busy"
            />
            Fulfilled
          </label>

          <p class="total">Total: <span data-testid="total">{{ total }}</span></p>

          <div class="actions">
            <button
              class="primary"
              data-testid="save"
              type="submit"
              :disabled="busy"
            >
              Save
            </button>
            <button
              data-testid="reset"
              type="button"
              :disabled="busy"
              @click="resetDemo"
            >
              Reset demo
            </button>
          </div>
        </form>

        <div v-else class="actions">
          <button
            data-testid="reset"
            type="button"
            :disabled="busy"
            @click="resetDemo"
          >
            Reset demo
          </button>
        </div>

        <p class="feedback" data-testid="feedback" role="status">
          {{ feedback }}
        </p>
      </section>
    </div>
  </main>
</template>
